version: 2
jobs:
  build:
    steps:
      - checkout
       - run:
          name: Install Platform.io
          command: pip install -U platformio
       - run:
          name: Build Application
          command: - platformio ci --project-conf=platformio.ini
