version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python --version
            pip install -q platformio --user
      
      - run:
          name: Build Application
          command: |
            platformio ci --project-conf=platformio.ini
     
          
